# Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# CPC-2 specific overrides

eventBus:
  clusterId: "2"
  # CPC-2 specific mTLS permissions
  auth:
    permissions:
      mtls:
        mqtt-client:
          identity: "CN=mqtt-client.cpc-2"
          account: "CPC"
