ruleset_overrides:                                                        # Enables override of specific rule severity (per ruleset). Naming must match one to one.
  standard-owasp:
    owasp:api8:2023-no-scheme-http: "warn"
