apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  # Configuration file that can be mounted as a volume
  config.yaml: |
{{ .Values.serviceConfig | toYaml | indent 4 }}
